import dotenv from "dotenv";

dotenv.config();

const { DISCORD_TOKEN, CLIENT_ID, GUILD_ID, AMP_USERNAME, AMP_PASS, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB } = process.env;

if (!DISCORD_TOKEN || !CLIENT_ID || !GUILD_ID || !AMP_USERNAME || !AMP_PASS
    || !POSTGRES_USER || !POSTGRES_PASSWORD || !POSTGRES_HOST || !POSTGRES_PORT || !POSTGRES_DB) {
    throw new Error("Missing environment variables");
}

export const config = {
    DISCORD_TOKEN,
    CLIENT_ID,
    GUILD_ID,
    AMP_USERNAME,
    AMP_PASS,
    POSTGRES_USER,
    POSTGRES_PASSWORD,
    POSTGRES_HOST,
    POSTGRES_PORT,
    POSTGRES_DB
};
